// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuD-kRmz1eSGxfoZNCwoTp-CaM8rLBRrU',
    appId: '1:353555396732:web:453801dc7deb22363b31f9',
    messagingSenderId: '353555396732',
    projectId: 'cla-man',
    authDomain: 'cla-man.firebaseapp.com',
    storageBucket: 'cla-man.appspot.com',
    measurementId: 'G-LDZ822ESGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFC3Rvqv718bnTJtO9VSw0TFbdSgMOFw',
    appId: '1:353555396732:android:67a088d01cf7dba63b31f9',
    messagingSenderId: '353555396732',
    projectId: 'cla-man',
    storageBucket: 'cla-man.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeTI8pDr5QN0yHTfrSsr9RpjzfY3WNGpE',
    appId: '1:353555396732:ios:7e4ed37a5f328e533b31f9',
    messagingSenderId: '353555396732',
    projectId: 'cla-man',
    storageBucket: 'cla-man.appspot.com',
    iosClientId: '353555396732-2aks8cvl7eudoqbtv7i02iijk1d1j5ln.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.classManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeTI8pDr5QN0yHTfrSsr9RpjzfY3WNGpE',
    appId: '1:353555396732:ios:97292a8c09ba09a63b31f9',
    messagingSenderId: '353555396732',
    projectId: 'cla-man',
    storageBucket: 'cla-man.appspot.com',
    iosClientId: '353555396732-58ijsho22j7svdj158ip1s96sbe9qgfu.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.classManager.RunnerTests',
  );
}
